export let tags = {
    'Show all': 'primary',
    'algorithms': 'info',
    'assembly': 'success',
    'bioinformatics': 'primary',
    'c': 'secondary',
    'c++': 'primary',
    'cmake': 'danger',
    'food': 'warning',
    'gamedev': 'danger',
    'js': 'success',
    'ide': 'info',
    'logic': 'warning',
    'lldb': 'info',
    'lims': 'warning',
    'math': 'secondary',
    'movies': 'info',
    'nim': 'warning',
    'other': 'info',
    'python': 'success',
    'rust': 'danger',
    'shortstory': 'success',
    'tech': 'success',
    'thoughts': 'secondary',
    'vscode': 'info',
    'wasm': 'danger'
}