export let tags = {
    'Show all': 'primary',
    'assembly': 'success',
    'bioinformatics': 'primary',
    'c': 'secondary',
    'c++': 'primary',
    'cmake': 'danger',
    'food': 'danger',
    'logic': 'warning',
    'math': 'secondary',
    'movies': 'info',
    'other': 'info',
    'python': 'success',
    'rust': 'danger',
}